version: '3.7'

services:
  flashcards_backend:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

networks:
  default:
    name: flashcardsnetwork
    external: true

volumes:
  data:
    driver: local
